// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNB98-6MbkfK82k6sEc1GkGU9Tc2MxP6g',
    appId: '1:526791122322:web:7a2aa3cfe9664ba63c354b',
    messagingSenderId: '526791122322',
    projectId: 'mobileapp-db-620ea',
    authDomain: 'mobileapp-db-620ea.firebaseapp.com',
    storageBucket: 'mobileapp-db-620ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWUbrBzzdlfq17A3eUD35fv5AMO3_v270',
    appId: '1:526791122322:android:c5979b13da1df6653c354b',
    messagingSenderId: '526791122322',
    projectId: 'mobileapp-db-620ea',
    storageBucket: 'mobileapp-db-620ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDgq1YsgRD14yGyZVPqve-tP9V1v-F_E',
    appId: '1:526791122322:ios:a7def50491c26f2f3c354b',
    messagingSenderId: '526791122322',
    projectId: 'mobileapp-db-620ea',
    storageBucket: 'mobileapp-db-620ea.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNDgq1YsgRD14yGyZVPqve-tP9V1v-F_E',
    appId: '1:526791122322:ios:a7def50491c26f2f3c354b',
    messagingSenderId: '526791122322',
    projectId: 'mobileapp-db-620ea',
    storageBucket: 'mobileapp-db-620ea.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNB98-6MbkfK82k6sEc1GkGU9Tc2MxP6g',
    appId: '1:526791122322:web:28605fe4040dd4c13c354b',
    messagingSenderId: '526791122322',
    projectId: 'mobileapp-db-620ea',
    authDomain: 'mobileapp-db-620ea.firebaseapp.com',
    storageBucket: 'mobileapp-db-620ea.appspot.com',
  );
}
